### PR TITLE
newer buildroot branch and host kubeadm

### PR DESCRIPTION
**Pull request by whooo**
Switch to the latest stable buildroot branch and build a host version of kubeadm for generating the image list.

Both commits should stand on their own if you don't want one or the other

### CODE REVIEW

**Comment by afbjorklund** [comment]
My plan was to go for 2022.02.x LTS branch, which is around the corner. But thanks!

**Comment by whooo** [comment]
I suspected that, but you wouldn't mind taking https://github.com/afbjorklund/buildroot4kubernetes/pull/15/commits/4cfc9bb7560a41fe22f300a45da62c4d689e7b21 as it made it slightly easier to build on a distribution without kubeadm?

**Comment by afbjorklund** [comment]
Having a host kubeadm sounds good, I just downloaded the matching binary locally and put it in the PATH.

https://www.downloadkubernetes.com/

I suppose you _could_ also just supply the image list in text (or json), but that is also more maintenance.

Unfortunately upstream doesn't produce any image lists or image archives, that would have been nice to have...

**Comment by whooo** [comment]
I might have found a way to download the container images without using docker but using skopeo instead.
I'll close this PR and continue working in my git repo, you know where you can fetch these commits if you want

**Comment by afbjorklund** [comment]
Added support for host kubeadm and host kubectl, using the regular Config.in.host setup from buildroot

57411e499621284ccfe0bdef81bffdb1676ce2de

**Pull request closed without merging**
